---
sudo: required
language: python
services:
  - docker
env:
  global:
    - access_key_id:
        secure: "yNeUI8Dp59iGMsKsG0oYIpcKgnchScPlri1cudPLfwBF1uJRMQt29qqpn5gIkB9zHNR895Zu4lZ7P9F1sdr9J464nrmy9fs/Kqp/4T1e6qtgcJqpACFavQbPw19zU5jM8MnNckghmMcGYUhJhyrIyOmSo1HGNG0bi4vMQl9WOrHX73HORDU7/JRh6eDU1HhNddJqz2X1niIrifetdfxUSijc6/yU87RyKSegh8OFNZGwutvZ+qoMn/SvBVtNlb1FDUKnLaMCqahoUPIHrfESMlloWdH8ymk8mqu8JGmhKBVGAzeIQ62LK24fMa2+6daF+g0WvXXXIMDQ5OaWiFVMYf6TpUrJ2ItBrQhJEnrdbsWGF967PbOr1P+B1muqLG9ejTe8Y5cJOj8m7028eauF2d0ErzApaIW8/ZHm++049NwJVBxPHNoT5lrLyRj2D7CIuxQLzO+JCF/sZB5aA6j/vNWrCT7V5FyG0s2os9ujfGaHFrbXlEEJZ04AnNxrI3bn3Z+M8X8gqtNHG99xLb0hf56hRIBHeWvR8DcWoLvvsmEzqaSGNtySQ1Tne8EoVu1Kp1ku86f1uZ5p1RpzAYkfQ7wZjorrSk2nT1hWiHVzGQlAHe6weiNJkxNra4UXNqU6luxSH9qf6N4fqZTy2ic36/jZFBYqUCTf+NnFiEwMMho="
    - secret_key:
        secure: "K7NBjVitQ2XFdjOCG9EMO7NBbHQdhXoDK/MYbE5L6kPbhjh4Mbj7eOTqgPNkP+ykXKiSVuVVRNqem730833hq/jn9twbDdjQePFL6lZuTMH0NWXedyJ0zVwAkq83YnrCQNFZTDoD12GJr5CPYzoPb36wK+MjbS1THlpnoAhm8TyMwAVTHhgRHvvG60ExH4/An7PVBa1DfnDpGeC3om3PTw1uuk7qMSQ+X/1jIP7wTxyfnIvuFMEy7AaJuTn1CaIzPc58VvH01I1tCArWqrxF9ff0QLzYLn42Iu3hh3BwrG1N9BmEzATjtKlwRI41NmspyNjqxR1iMtS/Cfj08eNvNS2jpM6EI08Kyt9MLgM3HM5O7ik8kmF32/agpS5IVywdK6ruq6L0k9ppWT2KbAKOjVDUTTf4qv6ddqWW7M6TAYuiA5ZrvmGohNCtDnUb3f/Yvsbvl5kEER2aWxv8Peyqwkc3W0y63AN0vNxyY5OXGGi+wNxtRPCoo9UASKtF0TZ6/D/ASUs2f9Gu7Y2hMgMbzKVqTlenPUDx0GO6NpcIYK2rQHtOCb7HANpaSY5zKJ8QlBavN/SMADOvKmuyYAT8PhyiJ7gpYuwGLxbo0xPKf6+4T9scZYk7CHw2nUTKMRMtUb3NiSGBYlojPrQj5NuGHgARfhLb79VhrlT1B54qYSs="
install:
  - pip install molecule
  - pip install docker

branches:
  only:
    - master

script:
  - molecule --debug test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
