---
sudo: required
language: python
services:
  - docker
env:
  global:
    - secure: "IBN2SAWAhaMzOC3CLfKEDZyCBAx8zSKQzI7wRZXZbiTVK3cFb10bm5VubV6CaS1/F3oxX6TxmkebEMMZA5ckQspUGVB3oCn3eEAz//CPiiDlvKdDek5Vl6OuoyCenu+q9vUYDhM4jy9ebXsfVg7H+yka4WUYqIKbOyUduOV3WeBKqveUsF1XRTdPItPUCJUsaTTclZjotASfuegFeeccfxT0Qe6UfbZCNi6o2dYgZ8PBV7xCvSr4xfSL4QWx6myvCyjoCodMCaymj+tb9AvoqJIZbJVj9Vxp1JAlZ++QL2qJkWgV6tVMaJt/OwRBNug+FOm8wVo8RVXdsbQ0oKA7g7Yj6PokPRgcqKKbQCIIqXL4ZCccDYFoEKBHf7E3ncU01gUQZR8RwQL7Wgr37ZwqoQpx0eh1WfEAVIaLDfgF2nsIBFJboiPNvrL88SemH2ritQx7afTeupz8JN9kk7iPHusW9RsQ8xlE2YkMxq1WR3KyW82HLNmJ7OYuLkuMKO7V6HObQb00Dx0nKPaysULAxDbNYnfWtXn0f1oBXHRpTRjpcyti+uMPzyfYVifc9ThgOpY8fpIB2+S8/TK+2zOqbrrHY6lJXsIZbqCJuJeOuCgF4jf1O0TmItjj086CYrWptKrfM9ascwgys+DQ3zRAyrdPMcayUBX8vvqOUcRxcXo="
    - secure: "ti/R2N8L4bHCnoONWaEg9sjAIzcZg84PfAtxcf749z49gS4gQ3eoGjkVIUmSfkfqzjS40WUGPtNFw++3J+ZxcDw2wx3JTFaL2WqHK5HyMagTJrQ4cK8QgrPyJYZ1ozGLdgkpBMps+u93rd6hygRiZEpzIrl23GnS37UJd5lQSaEP55f3Shzckud/ss8nzrHSV37jBuWqu5/bHVU6KdYP1ka8kpqOInG6s4QldWodgB56wei5SReF0Zo7QJowB74CHWQADfiQDYjIX0iFFJVdVYutz1cwvwPF9iJ7Kv3psPPFbjT8Xs9xZscYFk1BJ5FxZdBlnd6s3G4DekDQ7CT5BL7kIGwIJhMikuXx7oy2M+lp3B7sRYZruQPfFfJ/bBLcJ8SLny+kavTia/ZwaioCg8T+BN3qYJsF45GqbPbVfxcYv7DvuEhcPsqwM6yYNMmSctSEAlZgf0Y4qA6apUbVnNXQDkmCj0mWS7EsRAJfqMwFHBEWXCdZ1f7E36TxD/fX4jPi/JlSRKH9YFbNrXzMj9Gu6UFR0dGJjNHWU4H0zXhkH2rm+aotnrDMT4S15E4FgmDgN76eAVg2fK+0Y8Oz7veIRyWlggf6uyOtgMcErG/wK4Kbj9bOob/hBgQSlL4o4//HELcqGD2kcX9ChBWOQSA0k4qm2MMO/C10e09GiPE="
install:
  - pip install molecule
  - pip install docker

branches:
  only:
    - master

script:
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
