---
sudo: required
language: python
services:
  - docker
env:
  global:
    - secure: "j0IiiGeTTmVeW+jmazmzfUpRw5T6WaTfSt7tjDQrWeisZdsSiKEKBytBgrnE+kfNB9wmyeT++q7HzxsEaIumgk0ThdjBBE90IIS3lhDdYJnlmwtBWxQiQqBn3EEgPrJrR9j69YAZP1vntrCGZN7gjQAVcMXCv64y0eP9hXvQS++2l3NZ2MzPUaToz0GkVOvEhhFGrjzbpjdm/3pPifzSdmh/LyFa7whgDltEltVlZYj+xVdIwCHYbnyRC6TuBwEvuppteqLPKTwFe8cOwsRdVAr0K71o2PCxA6XI6z6dhPs9DDS4e0ldSyyuc/jOGoNmxBVK7ggyqqIgExKGin5mWOJVOMBsBvoiRJBSEnZQCgwu76mvOc45MxYeXayP2US5JKb5guRFUl0NscTjD0e2yfRd6HMhsEaOmZuvztksfei9lr7PFNYfP4CHusNCNMTCEEi6qashSPnldQKadN8p6W6bpXDcJS841RvwAAjG21rAkC1J6tWniTW4CRACargCiruX43WHpZEwQ+bkECiJX6k0W4uiKS3NW1WFPGFdLO+5dh8Rk/JewINl/yVuXanb+LOIkV0Z+s5JJIhdkjKsCv2KrDykaFFoX2x06O1WVxZazpHNwZ3ppdg0stISJHbWrihMoJULdPFAjoAPolG3u1OT3JV2DVFgvLB1QFKDBlA="
    - secure: "kDK84CkyCEZhi61WBCzHUCiKkQj1sWvpxOAkXVG6GmJw1H8Fxb3RnORpO2qag0Umy6RY4DXdJPR8LVlQfGjqSxhEhFdA+kN3Tnc4M/iGJZwPw6lCKEPvTNkejM2kEXLeUT3i+FRMBf1KEv7Qi3EX1POaeszxw8RyUkTQBI/Ob12/av5X6XjZDbQocyYNB4Sk6+BgRYBvYlUJAaxeKRVWoZ3uWXbjL8XDo16Kk9bGbDb7iCtUt3tVn6LbUwA+hphximHxjGLYwGQXuecnxDZFxYwRBZ67GSvcvi2K4CF+SIidGxFOYTIvzHZOtKM5wxfPnCZABF9kkejSq9JH1VahrWSE8kXFl4MOrj8uhhS9BZePChD+Ygw8lZKFdqLzU4Idp12Dt6c10C7Co+6KTFdzJaNyPX1xTgK+KqGFnBmw8kglwZ69sviTklYWwFJd/vK5AxQXHNlczRzOraKhJ/VDVfHJV3VDgdZjYrx80eHra+Baboqi0yIoH5H3L90bVL4u+s5uRh2Jns1cjwnA5qd61Um7FVnoKgIdH4AFgDK5RAbiRCwq131wWAVnTWMZMptVpAWXhx0CRk/lQefDi0J984pUh3xTFwkxG3z/8u4/NG7Yemq4/eSkVslKArKfJaPdRQC7DVo3HGInzDBtupTC8H+kpPbrJqhtaMPECVAMrjE="
install:
  - pip install molecule
  - pip install docker

branches:
  only:
    - master

script:
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
