---
sudo: required
language: python
services:
  - docker
env:
  global:
    - secure: "l8QO66DzIyV6f+9JB+AT9cz9Ej0ZZGidZs4Ia3beE+qSnv5TsweTWEEDae/r5gjzClSHmg6Eu27IRR8XQFG0FjYVgweW8n2K6Rhx5jBaaHdPyViKiVTY8KjDSSNqnXEOjl5GS6oRAyNHQM/mxa/X9YYUtBsbLaKt6LnG2w5vzNFGfyhBWvcW10lcoNK2H5R9qIUkSLaSqpiDd0/porsT3Fed1ZWnoQGsAj6KrrLU/ZTMzfzVqb34kWx1Lfmx1vTodospGG4i7iHc1i6oAmQRZ2v9VKgoBmviqgIwdZjaXWWnnQwS82iYxqxgn5xi6DjckjLLxv1RqNXJEtU8H2TXaEIPXNQIQkyijyXNX25U7L41sNbxSLQOnvXAApROZo/JJbr/dLuyhLM786c8udqbbbQRHXOHhw+mbeq7z2/ydQtrEq6S21dIAi4Q/yhYOhb+ZnOvy3CMB2An80HBPUC9hJGWLmvUpd4WkGNcAzU4jvPhDh+G/1D//pVHeB/oYl0tJ+u1qzXfAagiCx+UKowBlCdACaFwEqVJ5fl7Q/DEUJONWm5nBwY3PykkEWQXCtqFlXjQ+8clDz+59L8kivBDbkJhjz0deL+UOXqIhtMu6yLSBz5+7uSJXJQyGVya7NxXQZ5N48iqK6+43yuMYKleY2zpnj16NuaL/16qT6PQQ34="
    - secure: "dyp8WmSk1e8wuwu8MfaCIat9F8KVdugAnnf0mV5h+YuUfCSX0Pl4sdZU6PAlqzA46nvJs8I5+5TW8j6IZ/At4cT5eTO4OPKhBaB/9eU/1h4/+AH21y8hoNb3/TmRKKvxPcUgnp1QEwEUcn+oFV3NQ1aTTivb186fv7p+JIDRgam0N6Mcu5cVO7xxkAamK4lzqkB/vimSSOybmHZN9jjeYs2BhkiRDKTZHb4uARHYnlpcLdY+fVmmiHhIr6UcgR8CBTrYYGJnQUDBHNluFyQre/t/7/8G6BrLvVz29W4+eNWdt9I2YJPpxQjZnEQ2Do38mYz6LGBZJPT1Qsb8uoxn3lj7dnzR/N5JhStmCwQT6RbTyTTNHqa8LUSuAfSZHsJr76up5p1SlTnIDWDA3T2GxH88k1BmlcyA2WcXu5Z0BIdJc4ca/uJ6C1rv4ayfF63sfYjvV4faeo9c+4vWHppe/AqYsHY9rQklmc7uGUNoDIMPLhM8xFrPQcAKV/STcQxCyne6hxMhqQi2e7gniVEcLHoTmgYv7zXyP8cMgxVMj9+pBlbsEvNZa7ep8G385LjG/G5jZXo5wsUc2zNGyB3gKbpAozduvOjFwguEu12SxyUWSQn1svOGQlzaZ6v9SLIsiEPqwtYH+ijCbQ468F+wtQ3iSnbWp1Mo/lfmzCiSkRs="
install:
  - pip install molecule
  - pip install docker

branches:
  only:
    - master

script:
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
