- name: Determine downlod URL for CentOS
  set_fact:
    cloudwatch_agent_download_url: https://s3.amazonaws.com/amazoncloudwatch-agent/centos/amd64/latest/amazon-cloudwatch-agent.rpm

- name: Designate downlod directory
  set_fact:
    cloudwatch_agent_download_directory: "/home/{{ cloudwatch_agent_username }}/Downloads"

- name: Designate download directory username
  set_fact:
    cloudwatch_agent_username: "{{ cloudwatch_agent_username }}"
