---
# Prerequisites. Attach role to EC2 instance with cloudwatch permission to
# Support Ubuntu, Debian, CentOS, Amazon Linux 2

- name: Setup for Ubuntu
  include_tasks: "ubuntu.yml"
  when: ansible_distribution == 'Ubuntu'

- name: Setup for CentOS
  include_tasks: "centos.yml"
  when: ansible_distribution == 'CentOS'

- name: Designate downlod directory
  set_fact:
    cloudwatch_agent_download_directory: "/home/{{ cloudwatch_agent_username }}/Downloads"

- name: Designate download directory username
  set_fact:
    cloudwatch_agent_username: "{{ cloudwatch_agent_username }}"

- name: Directory to store downloaded CloudWatchAgent binary package
  file:
    path: "{{ cloudwatch_agent_download_directory }}"
    state: directory
    owner: "{{ cloudwatch_agent_username }}"
    group: "{{ cloudwatch_agent_username }}"

- name: Download CloudWatchAgent
  get_url:
    url: "{{ cloudwatch_agent_download_url }}"
    remote_src: true
    dest: "{{ cloudwatch_agent_download_directory }}"
    owner: "{{ cloudwatch_agent_username }}"
    group: "{{ cloudwatch_agent_username }}"

- name: Install the package
  apt:
    deb: "{{ cloudwatch_agent_download_directory }}/amazon-cloudwatch-agent.deb"
  when: ansible_distribution == 'Ubuntu'

- name: Install the package
  yum:
    name: "{{ cloudwatch_agent_download_directory }}/amazon-cloudwatch-agent.rpm"
  when: ansible_distribution == 'CentOS'

- name: CloudWatchAgent configuration
  template:
    src: aws-cw-config.json
    dest: /opt/aws/amazon-cloudwatch-agent/bin/config.json

- name: Start the CloudWatchAgent
  command: >
    "/opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl
    -a fetch-config
    -m {{ aws_cloudwatch_agent_mode }}
    -c file:/opt/aws/amazon-cloudwatch-agent/bin/config.json -s"
  args:
    creates: /opt/aws/.ansible-creates-start-CloudWatchAgent
  notify:
    - creates start CloudWatchAgent
